---
orchestrator_hostname: localhost
orchestrator_addr: 127.0.0.1
orchestrator_fe_ipc: client_ipc
orchestrator_be_ipc: server_ipc
block_size_gb: 1000
min_block_size_gb: 100
client_port: 35010
server_port: 35020
log_server_addr: 127.0.0.1
log_server_port: 35030
log_server_sync_port: 35031
simulation_addr: 127.0.0.1
simulation_port: 35040
s_visualisation_port: 35050
o_visualisation_port: 35055
transport: tcp
sched_strategy: round_robin
res_catalog: inmemory
simulation:
  nb_clients: 1
  nb_servers: 1
...
