orchestrator_hostname: localhost
orchestrator_addr: 127.0.0.1
orchestrator_fe_ipc: client_ipc
orchestrator_be_ipc: server_ipc
client_port: 35000
server_port: 35001
transport: tcp
sched_strategy: worst_case
simulation:
  nb_clients: 1
  nb_servers: 1
