hosts:
  - hostname: infra_multi_node_multi_disk_1
    ipv4: 10.0.0.1
    network_bw: 25 #GBps (100Gb Eth)
    disks:
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ9342009D8P1HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme0n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ93420AFN8P2HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme1n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ9342009D8P3HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme2n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ93420AFN8P4HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme3n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ9342009D8P5HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme4n1
  - hostname: infra_multi_node_multi_disk_2
    ipv4: 10.0.0.2
    network_bw: 25 #GBps (100Gb Eth)
    disks:
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ9342009D8P1HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme0n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ93420AFN8P2HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme1n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ9342009D8P3HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme2n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ93420AFN8P4HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme3n1
      - vendor: INTEL
        model: SSDPE2KX080T8
        serial: BTLJ9342009D8P5HGN
        capacity: 1600 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme4n1
  - hostname: infra_multi_node_multi_disk_3
    ipv4: 10.0.0.3
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd0
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd1
  - hostname: infra_multi_node_multi_disk_4
    ipv4: 10.0.0.4
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd0
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd1
  - hostname: infra_multi_node_multi_disk_5
    ipv4: 10.0.0.5
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd0
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd1
  - hostname: infra_multi_node_multi_disk_6
    ipv4: 10.0.0.6
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd0
      - vendor: SEAGATE
        model: HDDAPE2KX080T8
        serial: BTLJ934100LT8P6HGN
        capacity: 2000 #GB
        write_bandwidth: 0.05 #GBps
        read_bandwidth: 0.1 #GPBS
        block_device: /dev/hdd1
