hosts:
  - hostname: ault14-1
    ipv4: 148.187.104.85
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ9342009D8P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme0n1
      - vendor: INTEL
        model: SSDPE2KX080T2
        serial: BTLJ93420AFN8P0HGN
        capacity: 2000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme1n1
      - vendor: INTEL
        model: SSDPE2KX080T2
        serial: BTLJ934100UU8P0HGN
        capacity: 2000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme2n1
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ934107408P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme8n1
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ9341075B8P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme9n1
  - hostname: ault14-2
    ipv4: 148.187.104.86
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: INTEL
        model: SSDPE2KX080T5
        serial: BTLJ934100LT8P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme7n1
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ934107408P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme8n1
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ9341075B8P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme9n1
  - hostname: ault14-3
    ipv4: 148.187.104.87
    network_bw: 12.5 #GBps (100Gb Eth)
    disks:
      - vendor: INTEL
        model: SSDPE2KX080T5
        serial: BTLJ934100LT8P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme7n1
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ934107408P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme8n1
      - vendor: INTEL
        model: SSDPE2KX080T1
        serial: BTLJ9341075B8P0HGN
        capacity: 1000 #GB
        write_bandwidth: 2.93 #GBps
        read_bandwidth: 3.13 #GPBS
        block_device: /dev/nvme9n1
